import sys

def xlate(movx,movy):
	nums = [8,7,6,5,4,3,2,1]
        alph = ['a','b','c','d','e','f','g','h']
	movelet = []
	movalph = alph[movy]
	movnum  = nums[movx]
	movelet.append(movalph)
	movelet.append(movnum)
	return movelet

def purtyprint(movlist):
	translist = []
	#my ass-backward grid goes +x down columns and +y across rows so my_shitty_grid[a][b] should translate into my_shitty_grid letters[b], nums[a] once this layer is finalized no harm done with the out of order indices. i dont think this project is going to get deep enough to worry about writing lasagna code
	for x in movlist:#movlist is what is generated by legal_moves.py or whatever i called it
		move = []
		startmov = xlate(x[0],x[1])
		endmov   = xlate(x[2],x[3])
		move.append(startmov)
		move.append(endmov)
		translist.append(move)
	return translist
		
	
